insert into vacunas (pk_vacuna, nombre, observacion) values (1, 'Parvovirus', 'aplicarse a las 6 semanas de vida');
insert into vacunas (pk_vacuna, nombre, observacion) values (2, 'Moquillo', 'aplicarse a las 6 semanas de vida');
insert into vacunas (pk_vacuna, nombre, observacion) values (3, 'Adenovirus/Hepatitis', 'aplicarse a las 6 semanas de vida');
insert into vacunas (pk_vacuna, nombre, observacion) values (4, 'Leptospirosis', 'hace mucha actividad en el exterior, esta vacuna es importante');
insert into vacunas (pk_vacuna, nombre, observacion) values (5, 'Traqueítis infecciosa', 'Para los que van a residencias o casas de acogida');
insert into vacunas (pk_vacuna, nombre, observacion) values (6, 'Leishmania', 'en zonas donde el mosquito que la transmite es muy común');
insert into vacunas (pk_vacuna, nombre, observacion) values (7, 'Rabia', 'Obligatoria');
insert into vacunas (pk_vacuna, nombre, observacion) values (8, 'Parvovirus felino', 'ponerse sobre la sexta semana de vida de los gatos');
insert into vacunas (pk_vacuna, nombre, observacion) values (9, 'Herpesvirus', 'ponerse sobre la sexta semana de vida de los gatos');
insert into vacunas (pk_vacuna, nombre, observacion) values (10, 'Calicivirus', 'ponerse sobre la sexta semana de vida de los gatos');
insert into vacunas (pk_vacuna, nombre, observacion) values (11, 'Clamidófila', 'Para hogares con varios felinos');
insert into vacunas (pk_vacuna, nombre, observacion) values (12, 'Leucemia felina', 'prevención de la leucemia');